"""create product_name column on products table

Revision ID: 579dc7c87d4e
Revises: 49c170a7ee5a
Create Date: 2025-10-10 14:43:27.148509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '579dc7c87d4e'
down_revision: Union[str, Sequence[str], None] = '49c170a7ee5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('product_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'product_name')
    # ### end Alembic commands ###
