"""create image column

Revision ID: e5df4aacd431
Revises: 579dc7c87d4e
Create Date: 2025-10-29 22:17:19.775933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5df4aacd431'
down_revision: Union[str, Sequence[str], None] = '579dc7c87d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('product_image', sa.String(), nullable=True))
    op.add_column('products', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image')
    op.drop_column('order_items', 'product_image')
    # ### end Alembic commands ###
